sudo: required
services:
    - docker
before_install:
    - docker build -t chandu/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true chandu/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-360617681981"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

